### ISSUE TITLE
Error loading page: ValidationError: page.click: selector: expected string, got undefined

### ISSUE THREAD

**Issue by aznain** [dwsmart/massWebVitals#6]
Hi, 

I am getting this error when running the command 
```
node cwv input=example/input.csv output=example/output.csv
Testing with chromium 93.0.4530.0
example/input.csv - file successfully read
Testing 1 URLs
Error loading page: ValidationError: page.click: selector: expected string, got undefined
    at tString (/Users/dwt/Downloads/cww/massWebVitals/node_modules/playwright/lib/protocol/validatorPrimitives.js:44:11)
    at /Users/dwt/Downloads/cww/massWebVitals/node_modules/playwright/lib/protocol/validatorPrimitives.js:89:27
    at Proxy.<anonymous> (/Users/dwt/Downloads/cww/massWebVitals/node_modules/playwright/lib/client/channelOwner.js:64:99)
    at /Users/dwt/Downloads/cww/massWebVitals/node_modules/playwright/lib/client/frame.js:270:34
    at Frame._wrapApiCall (/Users/dwt/Downloads/cww/massWebVitals/node_modules/playwright/lib/client/channelOwner.js:77:34)
    at Frame.click (/Users/dwt/Downloads/cww/massWebVitals/node_modules/playwright/lib/client/frame.js:269:21)
    at /Users/dwt/Downloads/cww/massWebVitals/node_modules/playwright/lib/client/page.js:422:60
    at Page._attributeToPage (/Users/dwt/Downloads/cww/massWebVitals/node_modules/playwright/lib/client/page.js:202:20)
    at Page.click (/Users/dwt/Downloads/cww/massWebVitals/node_modules/playwright/lib/client/page.js:422:21)
    at getMetric (/Users/dwt/Downloads/cww/massWebVitals/cwv.js:107:28)
1 of 1  https://www.amazon.co.uk/ Error
creating example/output.csv
example/output.csv saved - done!
```

**Comment by aznain** [comment]
Yes , was removed. Thanks a lot for kind help.

**Comment by dwsmart** [comment]
Glad we got it fixed @aznain!
